
### root
#GET {{base}}/
#Accept: application/json


### check_mem_all

#GET {{base}}/check_mem_all/available?unit=G
#Content-Type: application/json
#Accept: application/json
#Authorization: {{auth}}


### check_mem

#GET {{base}}/check_mem/0?unit=G
#Content-Type: application/json
#Accept: application/json
#Authorization: {{auth}}



### launch - cuda

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "ag2sf",
    "sub_dir": "test1",
    "image_url":"http://127.0.0.1:8000/source_image/art_0.png",
    "audio_url":"http://127.0.0.1:8000/driven_audio/bus_chinese.wav"

  },
  "launch": {

  }
}



### task - status

#POST {{base}}/task/ss/status
#Content-Type: application/json
#Accept: application/json
#Authorization: {{auth}}
#
#{
#  "root_pid": "9417199",
#  "sub_dir": "test1"
#}
#
